### ISSUE TITLE
Замечания по lw0 (2)

### ISSUE THREAD

**Issue by lulldev** [Rabbit864/Calculator#1]
накатите prettier, посмотрите как изменится форматирование кода

**Comment by lulldev** [comment]
логические сравнения лучше использовать строгие !== / ===

**Comment by lulldev** [comment]
данный код сворачивается в 1 if:

```js
    if(signs[i] != ")"){
      if(signs[i] == "*" || signs[i] == "/"){
```

**Comment by lulldev** [comment]
countingNumbers -> calculateNumbers

функция не подсчитывает, а считает

**Comment by Rabbit864** [comment]
Поправил
